In [1]:
import torch

In [53]:
x = torch.ones(2,2, requires_grad=True)
print(x)

print(x.grad_fn)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
None


In [54]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [56]:
print(y.grad_fn)

In [57]:
z = y *y *3
out = z.mean()

print(z)
print(out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)
tensor(27., grad_fn=<MeanBackward0>)


In [46]:
a = torch.randn(2,2)
print(a)

tensor([[0.0538, 1.6851],
        [0.2400, 0.3107]])


In [47]:
a = ((a*3)/(a-1))
print(a)
print(a.requires_grad)

tensor([[-0.1704,  7.3790],
        [-0.9472, -1.3524]])
False


In [48]:
a.requires_grad_(True)

tensor([[-0.1704,  7.3790],
        [-0.9472, -1.3524]], requires_grad=True)

In [49]:
print(a.requires_grad)

True


In [50]:
b = (a*a).sum()
print(b)
print(b.requires_grad)

tensor(57.2048, grad_fn=<SumBackward0>)
True


In [58]:
print(out)

y.retain_grad()
z.retain_grad()
out.backward()

print(x.grad)
print(y.grad)
print(z.grad)
print(z.is_leaf)

out.backward()
print(x.grad)
print(y.grad)

tensor(27., grad_fn=<MeanBackward0>)
tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])
tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])
tensor([[0.2500, 0.2500],
        [0.2500, 0.2500]])
True


RuntimeError: Trying to backward through the graph a second time, but the saved intermediate results have already been freed. Specify retain_graph=True when calling backward the first time.

In [60]:
x = torch.ones(2,2, requires_grad = True)
y = x +2
z = y*y*3
out = z.mean()

print(out)

y.retain_grad()
# z.retain_grad()
out.backward(retain_graph=True)

print(x.grad)
print(y.grad)
print(z.grad)
print(z.is_leaf)

out.backward()
print(x.grad)
print(y.grad)

tensor(27., grad_fn=<MeanBackward0>)
tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])
tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])
None
False
tensor([[9., 9.],
        [9., 9.]])
tensor([[9., 9.],
        [9., 9.]])


<ipython-input-60-488d6104d8a2>:14: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the gradient for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations.
  print(z.grad)
